### ISSUE TITLE
Is it possible to reboot the remote server from this crate?

### ISSUE THREAD

**Issue by jethrosun** [jonhoo/openssh-rs#18]
For example, I need to reboot my servers before I start a new batch experiments. Is it possible issue a reboot from shell and then disconnect the local ssh handler?  Also, is it possible to run things in parallel? I have tried to use things like tokio::join but it doesn't seem to work nicely here. Thx!

**Comment by jonhoo** [comment]
You can reboot the server by running the remote command `sudo reboot`, if that's what you mean? You may then get an error from the ssh client though since the connection then also goes away.

As for running things in parallel, yes, that should work just fine. Just use `.spawn` to run two commands at the same time, and then join the resulting futures.

**Comment by jethrosun** [comment]
ok, so I can use .spawn to get the RemoteChild, how could I get the Future from it? Or am i not supposed to use tokio::join here? Thx

**Comment by jonhoo** [comment]
I'm not quite sure what you mean. There is no future associated with a `RemoteChild` itself. You get a future when you try to _do_ something with that `RemoteChild`, such as wait for it to finish, read its output, or something like that :)

**Comment by jethrosun** [comment]
Yeah, sorry about asking a vague question here, perhaps we can close it for now. I will have a closer look at this crate when I have more time later :)
